name = "cloudflare-ai"
main = "index.js"
compatibility_date = "2024-03-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SUBTITLE_KV"
id = "d2b887baaf9f4ddbad85f814fe5e836f" # User will need to replace this with their actual KV ID
